### ISSUE TITLE
Reflection issue in jdk 17+ with DEBUG requests

### ISSUE THREAD

**Issue by inhibitor181** [irsdl/IIS-ShortName-Scanner#31]
Hello,

Thanks you for the awesome tool, but is there any way of making DEBUG requests work on jdk17+ ? I have tried both `iis_shortname_scanner_jdk7.jar` and `iis_shortname_scanner.jar` but there is always the error

```
HTTPReqResponse() - Retry: 9
java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.net.www.protocol.https.DelegateHttpsURLConnection sun.net.www.protocol.https.HttpsURLConnectionImpl.delegate accessible: module java.base does not "opens sun.net.www.protocol.https" to unnamed module @763d9750
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at IISShortNameScanner.IIS_ShortName_Scanner.setRequestMethodUsingWorkaroundForJREBug(IIS_ShortName_Scanner.java:1538)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1401)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1520)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1520)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1520)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1520)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1520)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1520)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1520)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1520)
	at IISShortNameScanner.IIS_ShortName_Scanner.HTTPReqResponse(IIS_ShortName_Scanner.java:1520)
	at IISShortNameScanner.IIS_ShortName_Scanner.isReliable(IIS_ShortName_Scanner.java:1202)
	at IISShortNameScanner.IIS_ShortName_Scanner.doScan(IIS_ShortName_Scanner.java:544)
	at IISShortNameScanner.IIS_ShortName_Scanner.main(IIS_ShortName_Scanner.java:269)

```

The host was confirmed to be vulnerable using DEBUG requests via the `IIS Tilde Enum Scanner` burp plugin, but because of this error this tool does not find anything.

**Comment by sri2387** [comment]
did you fix thiis ?

**Comment by inhibitor181** [comment]
Nope, I used https://github.com/sw33tLie/sns instead that does not have this issue

**Comment by irsdl** [comment]
Did you run the jar file using the following command?

```
java --illegal-access=permit --add-opens java.base/java.net=ALL-UNNAMED -jar HARFILEHERE
```

Which Java version are you using? I know Java may not allow this in the latest versions.
